GET http://localhost:3000/api/cosmetics/

###

GET http://localhost:3000/api/cosmetics/caf40950-05d0-11ec-aa81-f95f8f736dad

###

POST http://localhost:3000/api/cosmetics/
Content-Type: application/json

{
    "brand": "Chanel",
    "name": "EyeLiner",
    "color": "Black",
    "price": "470kr"
}

###

PUT http://localhost:3000/api/cosmetics/e53a7500-05d1-11ec-aa81-f95f8f736dad
Content-Type: application/json

{
    "brand": "Filorga",
    "name": "Maskara",
    "color": "Brown",
    "price": "625kr"
}

###

DELETE http://localhost:3000/api/cosmetics/4
