GET http://localhost:3000/api/cosmetics/

###

GET http://localhost:3000/api/cosmetics/5968d290-05c9-11ec-824b-15fd2ebb3405

###

POST http://localhost:3000/api/cosmetics/
Content-Type: application/json

{
    "brand": "Filorga",
    "name": "EyeLiner",
    "color": "Gray",
    "price": "650kr"
}

###

PUT http://localhost:3000/api/cosmetics/5968d290-05c9-11ec-824b-15fd2ebb3405
Content-Type: application/json

{
    "brand": "Chanel",
    "name": "Serum",
    "color": "Transparent",
    "price": "625kr"
}

###

DELETE http://localhost:3000/api/cosmetics/"49eb7620-070d-11ec-a5b2-2f574789288c"